#!/usr/bin/env node
/**
 * sync-publish.mjs
 *
 * Vendor the X article publish JS template (Draft.js publish flow) from
 * the upstream workspace package into this standalone repo. Run before
 * release whenever the workspace template.ts changes.
 *
 * Workflow:
 *   1. Read   <workspace>/packages/publish/src/template.ts
 *   2. Read   <workspace>/packages/shared-types/src/index.ts (for PublishPayload)
 *   3. Inline the PublishItem / PublishImageAsset / PublishPayload types
 *      into the vendored template (so this repo doesn't need to depend on
 *      @x-article/shared-types)
 *   4. Write  src/vendor/x-article-publish/template.ts (committed snapshot)
 *
 * Usage:
 *   node scripts/sync-publish.mjs                       # default workspace path
 *   node scripts/sync-publish.mjs --workspace <path>    # explicit
 *   node scripts/sync-publish.mjs --check               # diff only, exit 1 if changed
 *
 * Default workspace location: ../x-article-workspace (sibling directory)
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { execSync } from "node:child_process";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");

const args = process.argv.slice(2);
const wsIdx = args.indexOf("--workspace");
const wsArg = wsIdx >= 0 ? args[wsIdx + 1] : null;
const CHECK = args.includes("--check");
const VERBOSE = args.includes("--verbose") || args.includes("-v");

const WORKSPACE = resolve(REPO_ROOT, wsArg || "../x-article-workspace");
const TEMPLATE_SRC = resolve(WORKSPACE, "packages/publish/src/template.ts");
const TYPES_SRC = resolve(WORKSPACE, "packages/shared-types/src/index.ts");
const VENDOR_DIR = resolve(REPO_ROOT, "src/vendor/x-article-publish");
const VENDOR_PATH = resolve(VENDOR_DIR, "template.ts");

if (!existsSync(TEMPLATE_SRC)) {
  console.error(`✗ workspace template not found: ${TEMPLATE_SRC}`);
  console.error(`  use --workspace <path> if the workspace lives elsewhere.`);
  process.exit(1);
}
if (!existsSync(TYPES_SRC)) {
  console.error(`✗ workspace shared-types not found: ${TYPES_SRC}`);
  process.exit(1);
}

const templateRaw = readFileSync(TEMPLATE_SRC, "utf-8");
const typesRaw = readFileSync(TYPES_SRC, "utf-8");

// Extract the PublishItem / PublishImageAsset / PublishPayload section verbatim
function extractTypeBlock(src, startMarker, endRegex) {
  const start = src.indexOf(startMarker);
  if (start < 0) throw new Error(`type marker not found: ${startMarker}`);
  const tail = src.slice(start);
  const m = tail.match(endRegex);
  if (!m) throw new Error(`type block end not found after: ${startMarker}`);
  return tail.slice(0, m.index + m[0].length).trim();
}

const publishItemBlock = extractTypeBlock(
  typesRaw,
  "export type PublishItem",
  /^\s*\|\s*\{\s*type:\s*"image"[^}]+\};/m,
);
const publishImageAssetLine = extractTypeBlock(
  typesRaw,
  "export type PublishImageAsset",
  /;/,
);
const publishPayloadBlock = extractTypeBlock(
  typesRaw,
  "export interface PublishPayload",
  /^\}/m,
);

// Build vendored template.ts: types inlined, original `import type ... from "@x-article/shared-types"` stripped.
const HEADER = `// AUTO-GENERATED by scripts/sync-publish.mjs — do not edit by hand.
// Source: <workspace>/packages/publish/src/template.ts (+ shared-types).
// To update: bump the upstream workspace, then run \`npm run sync:publish\`.

`;

const inlinedTypes = `${publishItemBlock}\n\n${publishImageAssetLine}\n\n${publishPayloadBlock}`;

// Drop the original import line; inject inlined types in its place.
const transformed = templateRaw.replace(
  /^\s*import\s+type\s+\{\s*PublishPayload\s*\}\s+from\s+"@x-article\/shared-types";?\s*$/m,
  inlinedTypes,
);

if (transformed === templateRaw) {
  console.warn(
    `⚠  Could not strip workspace import — vendored copy will reference @x-article/shared-types.`,
  );
}

const out = HEADER + transformed.trimEnd() + "\n";

const sha = createHash("sha256").update(out).digest("hex").slice(0, 16);

if (CHECK) {
  if (!existsSync(VENDOR_PATH)) {
    console.error(`✗ vendor file missing: ${relative(REPO_ROOT, VENDOR_PATH)}`);
    process.exit(2);
  }
  const existing = readFileSync(VENDOR_PATH, "utf-8");
  if (existing === out) {
    console.log(`✓ vendor up to date (${sha})`);
    process.exit(0);
  }
  console.error(`✗ vendor is stale. Run: npm run sync:publish`);
  console.error(`  expected sha256[0..16]: ${sha}`);
  process.exit(1);
}

mkdirSync(VENDOR_DIR, { recursive: true });
writeFileSync(VENDOR_PATH, out, "utf-8");
const lines = out.split("\n").length - 1;
console.log(`✓ wrote ${relative(REPO_ROOT, VENDOR_PATH)} (${lines} lines, sha256[0..16]=${sha})`);

if (VERBOSE) {
  try {
    const head = execSync("git -C " + JSON.stringify(WORKSPACE) + " rev-parse --short HEAD", {
      encoding: "utf-8",
    }).trim();
    console.log(`  workspace HEAD: ${head}`);
  } catch {
    /* ignore — workspace may not be a git repo */
  }
}
